name: WOKTutorial
version: '${project.version}'
main: woktutorial.woktutorial.WOKTutorial
api-version: 1.20
authors: [ vanessa ]
description: wok tutorial intro to mc plugin development
commands:
  fly:
    description: Toggles flying for the command sender, the player.
    usage: /fly
    aliases: f
    permission: fly
    permission-message: You do not have permission.
